### ISSUE TITLE
Slow `project-find-file` with bigger projects

### ISSUE THREAD

**Issue by alternateved** [buzztaiki/project-rootfile.el#6]
Hello!

I have noticed that `project-find-file` is now really slow (when working with bigger monorepo) while using package with below option enabled:
```lisp
(add-to-list 'project-find-functions #'project-rootfile-try-detect)
```

It may be worth to mention in README about this and e.g. advice to set variable `project-vc-ignores` like so:
```lisp
(setq project-vc-ignores
      '("node_modules"
        "target"
        "build"
        "output"
        "dist"
        "tmp"))
```
Or maybe somehow mitigate this slowness in package itself. What do you think?

Best wishes,
alternateved

**Comment by buzztaiki** [comment]
Thank you for your reporting.

`project-rootfile` delegates to a VC project backend if the target project is in VCS.
The reason for the slowdown seems to be that VC backend is not using VCS features (such as `git ls-files`) when a directory is specified (see [here](https://github.com/emacs-mirror/emacs/blob/5a223c7f2ef4c31abbd46367b6ea83cd19d30aa7/lisp/progmodes/project.el#L477) and [here](https://github.com/emacs-mirror/emacs/blob/5a223c7f2ef4c31abbd46367b6ea83cd19d30aa7/lisp/progmodes/project.el#L486))

I think it is possible to improve it, I will fix it tomorrow.

**Comment by buzztaiki** [comment]
@alternateved I have a few questions:
- Are those ignores included in your `.gitignore`?
- What emacs version do you use?

**Comment by alternateved** [comment]
Right, I should've attached it in the beginning.

Monorepo that I work with has `.gitignore` in root folder as well as in most sub-projects in the repository. Folders that I've listed in `project-vc-ignores` are not all in that global `.gitignore`, only some of them, but the local `.gitignore` (in the sub-projects) has most of them (like `node_modules`,`dist` `tmp`, `output`). 

Slowness that I've mentioned in this issue is happening when in any part of that monorepo I invoke command `project-find-file`. I have to wait a moment until anything happens at all. This does not happen with explicitly listing those directories with `project-vc-ignores` variable.

My Emacs version is `GNU Emacs 29.0.50 (build 24, x86_64-pc-linux-gnu) of 2022-05-13`. It was build with native compilation.

If there is anything that I could benchmark, check or provide in regards to that issue, let me know.

**Comment by buzztaiki** [comment]
I see. I got reproducible condition. Thanks!
